parent(manik,altaf).
parent(altaf,masum).
parent(altaf,mamun).
parent(altaf,masud).
parent(altaf,rita).
parent(masum,rumi).
parent(masum,jimi).
parent(masum,jeba).
parent(mamun,mun).
parent(mamun,rehan).
parent(mamun,soroni).
parent(mamun,shama).
parent(rita,rasna).
parent(rita,prova).
parent(masud,mumu).
parent(masud,sadman).
wed(altaf,feroza).
wed(masum,ruma).
wed(mamun,nina).
wed(masud,popy).
wed(rita,emdad).
wed(rumi,ringki).
wed(jimi,shahin).
wed(jeba,mithu).
wed(rasna,imam).
wed(rehan,fariba).
engaged(soroni,ishtiaque).


